#!/usr/bin/env bash


# Gets the current status of mpd (for us to parse it later on)
status="$(mpc --host $(pass mpd)@192.168.0.46 status)"
# Defines the Play / Pause option content
if [[ $status == *"[playing]"* ]]; then
  play_pause="pause (playing)"
else
  play_pause="play (paused)"
fi

# Display if repeat mode is on / off
if [[ $status == *"repeat: on"* ]]; then
    tog_repeat="repeat on"
elif [[ $status == *"repeat: off"* ]]; then
    tog_repeat="repeat off"
else
    tog_repeat=" Parsing error"
fi

# Display if random mode is on / off
if [[ $status == *"random: on"* ]]; then
  tog_random="random on"
elif [[ $status == *"random: off"* ]]; then
      tog_random="random off"
else
    tog_random=" Parsing error"
fi

# Variable passed to fzf
options="previous\nnext\n$play_pause\n$tog_repeat\n$tog_random"

# Spawn the mpd menu with the "Play / Pause" entry selected by default
chosen="$(echo -e "$options" | fzf --preview='mpc --host $(pass mpd)@192.168.0.46 -f "%artist% - %title% - %file%" current' --preview-window=up:wrap:noborder)"
case $chosen in
    previous)
        mpc --host $(pass mpd)@192.168.0.46 -q prev
        ;;
    $play_pause)
        mpc --host $(pass mpd)@192.168.0.46 -q toggle
        ;;
    next)
        mpc --host $(pass mpd)@192.168.0.46 -q next
        ;;
    $tog_repeat)
        mpc --host $(pass mpd)@192.168.0.46 -q repeat
        ;;
    $tog_random)
        mpc --host $(pass mpd)@192.168.0.46 -q random
        ;;
    "")
        exit
        ;;
esac
